# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://miguelsr.github.io" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: miguelsr
  avatar: gravatar.jpg
  gravatar: # Email MD5 hash
  description: "A place to blog" # used by search engines

  # Icons
  rss: false
  email_address: miguelsr87@gmail.com
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "MiguelSR"
  google_plus:
  instagram:
  linkedin: https://es.linkedin.com/in/miguelsr87
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: MiguelSR1987
  wordpress:
  youtube:

  # Scripts
  google_analytics: UA-63513599-1
  disqus_shortname: miguelsr
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Seguir"
  str_rss_follow: "Seguir feed RSS"
  str_email: "Email"
  str_next: "Siguiente"
  str_prev: "Anterior"
  str_continue_reading: "Continuar leyendo"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
